### ISSUE TITLE
Type 'x' does not conform to protocol 'TargetType'

### ISSUE THREAD

**Issue by GoNinja** [ivanbruel/Moya-ObjectMapper#18]
FYI
I'm having this issue on the latest version, if regress to version  1.3.0 this doesn't happens.

After making some searches I see people having the same problem, but they are using Carthage and its not my case.

This even happens with the Demo project (after doing pod update). And Xcode doesn't provide more info

**Comment by ivanbruel** [comment]
This was left hanging here for quite some time, sorry for the really late response.
This issue was due to the addition of `var multipartBody: [Moya.MultipartFormData]?` to the `TargetType` protocol.
I've updated the sample project in [afc7f9fb](https://github.com/ivanbruel/Moya-ObjectMapper/commit/afcf9fb0e9b4fa81ae3dce5622639694335f9fb2) which should fix this particular issue.

**Comment by iOSUser110** [comment]
HI,
I am still getting this issue even after adding multiform method..please update on this ASAP
